spring:
  profiles:
    active: production
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
---
server:
  port: 8083
spring:
  profiles: development, test
  data:
    mongodb:
      database: carts
---
spring:
  profiles: production
  data:
    mongodb:
      database: carts
