spring:
  profiles:
    active: production
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
---
server:
  port: 8083
spring:
  profiles: development, test
  data:
    mongodb:
      database: carts
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8080/uaa/userinfo
      token-info-uri: http://localhost:8080/uaa/introspect
      prefer-token-info: false
    client:
      client-id: app
      client-secret: appclientsecret
      access-token-uri: http://localhost:8080/uaa/oauth/token
      user-authorization-uri: http://localhost:8080/uaa/oauth/authorize
      scope: openid profile password
---
spring:
  profiles: production
  data:
    mongodb:
      database: carts