spring:
  profiles:
    include:
      - basic
security:
  oauth2:
    client:
      client-id: ${vcap.services.uaa.credentials.client_id}
      client-secret: ${vcap.services.uaa.credentials.client_secret}
      access-token-uri: ${vcap.services.uaa.credentials.url}/oauth/token
      user-authorization-uri: ${vcap.services.uaa.credentials.url}/oauth/authorize
      scope: openid,product.read,product.write,cart.read,cart.write
    resource:
      user-info-uri: ${vcap.services.uaa.credentials.url}/userinfo
      token-info-uri: ${vcap.services.uaa.credentials.url}/introspect
      prefer-token-info: false
logging:
  level:
    org.springframework.security: DEBUG