management:
  endpoints:
    web:
      exposure:
        include: ["hystrix.stream", "health", "info", "env"]
spring:
  data:
    mongodb:
      database: carts
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: ${vcap.services.zipkin.credentials.url}.apps.apbg.apcf.io/zipkin/
sample:
  zipkin: 
    enabled: true
feign:
  hystrix:
    enabled: false
  oauth2:
    enabled: true
security:
  oauth2:
    client:
      client-id: webstore
      client-secret: webstoresecret
      access-token-uri: ${vcap.services.uaa.credentials.url}/oauth/token
      user-authorization-uri: ${vcap.services.uaa.credentials.url}/oauth/authorize
      scope: openid,product.read,product.write,cart.read,cart.write
    resource:
      user-info-uri: ${vcap.services.uaa.credentials.url}/userinfo
      token-info-uri: ${vcap.services.uaa.credentials.url}/introspect
      prefer-token-info: false
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    registerWithEureka: true
    serviceUrl: ${vcap.services.discovery.credentials.uri}/eureka/
hystrix:
  shareSecurityContext: true