management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: nohystrix
hystrix:
  stream:
    queue:
      enabled: false
---
spring:
  profiles: discovery
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${vcap.services.discovery.credentials.uri}/eureka/
    fetch-registry: true
---
spring:
  profiles: hystrix
hystrix:
  shareSecurityContext: true
---
security:
  oauth2:
    client:
      client-id: ${vcap.services.uaa.credentials.client_id}
      client-secret: ${vcap.services.uaa.credentials.client_secret}
      access-token-uri: ${vcap.services.uaa.credentials.url}/oauth/token
      user-authorization-uri: ${vcap.services.uaa.credentials.url}/oauth/authorize
      scope: openid,product.read,product.write,cart.read,cart.write
    resource:
      user-info-uri: ${vcap.services.uaa.credentials.url}/userinfo
      token-info-uri: ${vcap.services.uaa.credentials.url}/introspect
      prefer-token-info: false
---
spring:
  profiles: gateway
zuul: # (3)
  routes:
    inventory-service:
      path: /inventory/**
      serviceId: inventory-service
      sensitiveHeaders:
      stripPrefix: true
    cart-service:
      path: /cart/**
      serviceId: cart-service
      sensitiveHeaders:
      stripPrefix: true
    product-service:
      path: /product/**
      serviceId: product-service
      sensitiveHeaders:
      stripPrefix: true
  ignored-services: '*'
---
spring:
  profiles: zipkin
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: ${vcap.services.zipkin.credentials.url}/
sample:
  zipkin: 
    enabled: true
