
spring:
  profiles:
    active: development
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
---
server:
  port: 8080
spring:
  profiles: development
zuul:
  routes:
    cart-service: /cart/**
    inventory-service: /inventory/**
    product-service: /product/**
  ignored-services: '*'
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
