# cf cs p-config-server standard config -c '{"git": { "uri": "https://github.com/apbg/microservices-config-repo" } }'
spring:
  profiles:
    active: development
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
---
server:
  port: 9999
  error:
    whitelabel:
      enabled: false
spring:
  security:
    basic:
      enabled: false
# security:
#   oauth2:
#     client:
#       client-id: app
#       client-secret: appclientsecret
#       access-token-uri: http://localhost:8080/uaa/oauth/token
#       user-authorization-uri: http://localhost:8080/uaa/oauth/authorize
#       scope: openid
#     resource:
#       user-info-uri: http://localhost:8080/uaa/userinfo
#       token-info-uri: http://localhost:8080/uaa/introspect
#       prefer-token-info: false
  profiles: development
zuul:
  routes:
    cart-service: /cart/**
    inventory-service: /inventory/**
    product-service: /product/**
    uaa-service: /uaa/**
  ignored-services: '*'
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/