management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: nohystrix
  autoconfigure:
    exclude: "org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration"
  cloud:
    circuit:
      breaker:
        enabled: false
    bootstrap:
      enabled: false
  rabbitmq:
    listener:
      simple:
        auto-startup: false
  sleuth:
    hystrix:
      strategy:
        enabled: false
management:
  health:
    rabbit:
      enabled: false
  endpoint:
    hystrix:
      stream:
        enabled: false
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 100000
        timeout:
          enabled: false
      circuitBreaker.enabled: false
      fallback.enabled: false
  metrics:
    enabled: false
  stream:
    queue:
      enabled: false
feign:
  hystrix:
    enabled: false
---
spring:
  profiles: discovery
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${vcap.services.discovery.credentials.uri}/eureka/
    fetch-registry: true
---
spring:
  profiles: hystrix
hystrix:
  shareSecurityContext: true
---
spring:
  profiles: security
security:
  oauth2:
    client:
      client-id: ${vcap.services.uaa.credentials.client_id}
      client-secret: ${vcap.services.uaa.credentials.client_secret}
      access-token-uri: ${vcap.services.uaa.credentials.url}/oauth/token
      user-authorization-uri: ${vcap.services.uaa.credentials.url}/oauth/authorize
      scope: openid,product.read,product.write,cart.read,cart.write
    resource:
      user-info-uri: ${vcap.services.uaa.credentials.url}/userinfo
      token-info-uri: ${vcap.services.uaa.credentials.url}/introspect
      prefer-token-info: false
---
spring:
  profiles: gateway
zuul: # (3)
  routes:
    inventory-service:
      path: /inventory/**
      serviceId: inventory-service
      sensitiveHeaders:
      stripPrefix: true
    cart-service:
      path: /cart/**
      serviceId: cart-service
      sensitiveHeaders:
      stripPrefix: true
    product-service:
      path: /product/**
      serviceId: product-service
      sensitiveHeaders:
      stripPrefix: true
  ignored-services: '*'
---
spring:
  profiles: zipkin
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: ${vcap.services.zipkin.credentials.url}/
sample:
  zipkin: 
    enabled: true
